/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
// useGLTF to load GLTF model into the canvas
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial, Color } from 'three';
import { TextureLoader } from 'three/src/loaders/TextureLoader'

export default function Model({ hue, saturation, lightness, uScale, vScale, textureIndex }) {
  // select which gltf model to load
  const { nodes } = useGLTF('../models/salmon/salmon.gltf')

  const textureVector = ['../models/salmon/food_0013_height_1k.png', "../models/salmon/1.jpeg", "../models/salmon/2.jpeg"]
  // load texture
  const texture = new TextureLoader().load(textureVector[textureIndex])
  // change the scale of the texture
  texture.repeat.set(uScale, vScale)

  const hslColor = extractColor(hue, saturation, lightness)
  const material = getMaterial(hslColor, texture)

  return (
    <group dispose={null}>
      <mesh
        name='head'
        castShadow
        receiveShadow
        geometry={nodes.head.geometry}
        material={material}
        position={[-0.671, 1.07, 0]}
        rotation={[0, 0, -0.289]}
      >
        <mesh
          name='front'
          castShadow
          receiveShadow
          geometry={nodes.front.geometry}
          material={material}
          position={[0.772, -0.013, 0]}
        >
          <mesh
            name='back'
            castShadow
            receiveShadow
            geometry={nodes.back.geometry}
            material={material}
            position={[0.857, -0.077, 0]}
          >
            <mesh
              name='finn_abv'
              castShadow
              receiveShadow
              geometry={nodes.finn_abv.geometry}
              material={material}
              position={[0.06, 0.594, 0]}
              rotation={[Math.PI, 0, 0.46]}
            />
            <mesh
              name='finn_abv001'
              castShadow
              receiveShadow
              geometry={nodes.finn_abv001.geometry}
              material={material}
              position={[1.378, 0.017, 0]}
              rotation={[Math.PI, 0, 0.46]}
            />
            <mesh
              name='finn_und_bk'
              castShadow
              receiveShadow
              geometry={nodes.finn_und_bk.geometry}
              material={material}
              position={[0.351, -0.394, 0]}
              rotation={[0, 0, 0.673]}
            />
          </mesh>
          <mesh
            name='finn_und_fr'
            castShadow
            receiveShadow
            geometry={nodes.finn_und_fr.geometry}
            material={material}
            position={[-0.146, -0.702, 0]}
          />
        </mesh>
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/salmon/salmon.gltf')

// assign the color and the map to the mesh material
function getMaterial(color, image) {
  return (
    new MeshStandardMaterial({
      color: color,
      map: image,
    })
  )
}

// convert color in HSL mode
function extractColor(hue, saturation, lightness) {
  return new Color("hsl(0, 100%, 100%)")
    .setHSL((hue ?? 0) / 360, (saturation ?? 0) / 100, (lightness ?? 0) / 100)
}