/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
// useGLTF to load GLTF model into the canvas
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial, Color } from 'three';
import { TextureLoader } from 'three/src/loaders/TextureLoader'

export default function Model({ hue, saturation, lightness, uScale, vScale, position }) {
  const { nodes } = useGLTF('/models/salmon/salmon.gltf')

  const texture = new TextureLoader().load('./models/salmon/food_0013_height_1k.png')
  texture.repeat.set(uScale, vScale)
  // const textureMap = extractMap(uScale, texture)
  const hslColor = extractColor(hue, saturation, lightness)
  const material = getMaterial(hslColor, texture/* , textureMap */)

  return (
    <group dispose={null}>
      <mesh
        name='head'
        castShadow
        receiveShadow
        geometry={nodes.head.geometry}
        material={material}
        position={[-0.671, 1.07, 0]}
        rotation={[0, 0, -0.289]}
      >
        <mesh
          name='front'
          castShadow
          receiveShadow
          geometry={nodes.front.geometry}
          material={material}
          position={[0.772, -0.013, 0]}
        >
          <mesh
            name='back'
            castShadow
            receiveShadow
            geometry={nodes.back.geometry}
            material={material}
            position={[0.857, -0.077, 0]}
          >
            <mesh
              name='finn_abv'
              castShadow
              receiveShadow
              geometry={nodes.finn_abv.geometry}
              material={material}
              position={[0.06, 0.594, 0]}
              rotation={[Math.PI, 0, 0.46]}
            />
            <mesh
              name='finn_abv001'
              castShadow
              receiveShadow
              geometry={nodes.finn_abv001.geometry}
              material={material}
              position={[1.378, 0.017, 0]}
              rotation={[Math.PI, 0, 0.46]}
            />
            <mesh
              name='finn_und_bk'
              castShadow
              receiveShadow
              geometry={nodes.finn_und_bk.geometry}
              material={material}
              position={[0.351, -0.394, 0]}
              rotation={[0, 0, 0.673]}
            />
          </mesh>
          <mesh
            name='finn_und_fr'
            castShadow
            receiveShadow
            geometry={nodes.finn_und_fr.geometry}
            material={material}
            position={[-0.146, -0.702, 0]}
          />
        </mesh>
      </mesh>
    </group>
  );
}

useGLTF.preload('/models/salmon/salmon.gltf')

function getMaterial(color, image) {
  return (
    new MeshStandardMaterial({
      color: color,
      map: image
    })
  )
}

function extractColor(hue, saturation, lightness) {
  return new Color("hsl(0, 100%, 100%)")
    .setHSL(hue / 360 ?? 0, saturation / 100 ?? 0, lightness / 100 ?? 0)
}